import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const TARGET_COUNT = 24;
const MAX_ATTEMPTS = 4;
const RETRY_DELAY_MS = 15_000;
const API_URL = "https://api.lolicon.app/setu/v2";

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const galleryPath = resolve(rootDir, "src", "gallery.js");

const gallery = await collectGalleryUrls();
await writeGallery(gallery);

console.log(`Generated ${gallery.length} gallery URLs.`);

async function collectGalleryUrls() {
  const urls = new Set();

  for (let attempt = 1; attempt <= MAX_ATTEMPTS && urls.size < TARGET_COUNT; attempt++) {
    const count = Math.min(20, TARGET_COUNT - urls.size);
    const batch = await fetchBatch(count);

    for (const url of batch) {
      urls.add(url);
    }

    if (urls.size < TARGET_COUNT && attempt < MAX_ATTEMPTS) {
      await delay(RETRY_DELAY_MS);
    }
  }

  if (urls.size < TARGET_COUNT) {
    throw new Error(`Only collected ${urls.size}/${TARGET_COUNT} URLs from lolicon API.`);
  }

  return [...urls].slice(0, TARGET_COUNT);
}

async function fetchBatch(count) {
  const url = new URL(API_URL);
  url.searchParams.set("r18", "0");
  url.searchParams.set("num", String(count));
  url.searchParams.set("size", "regular");
  url.searchParams.set("excludeAI", "true");
  url.searchParams.set("aspectRatio", "gte1.2");

  const response = await fetch(url, {
    headers: {
      "Accept": "application/json,text/plain,*/*",
      "User-Agent": browserUserAgent(),
    },
    signal: AbortSignal.timeout(30_000),
  });

  if (!response.ok) {
    const body = await response.text();
    throw new Error(`Lolicon API returned ${response.status}: ${body}`);
  }

  const payload = await response.json();

  if (payload.error) {
    throw new Error(`Lolicon API error: ${payload.error}`);
  }

  return payload.data
    .map((item) => item?.urls?.regular)
    .filter((urlValue) => typeof urlValue === "string" && urlValue.startsWith("https://"));
}

async function writeGallery(urls) {
  await mkdir(dirname(galleryPath), { recursive: true });

  const previous = await readExistingFile();
  const next = [
    "// This file is generated by scripts/update-gallery.mjs.",
    `// Updated at ${new Date().toISOString()}.`,
    `export const ARCHIVE_TAG = ${JSON.stringify(archiveTag())};`,
    "export const GALLERY = [",
    ...urls.map((url) => `  ${JSON.stringify(url)},`),
    "];",
    "",
  ].join("\n");

  if (previous === next) {
    console.log("Gallery is unchanged.");
    return;
  }

  await writeFile(galleryPath, next, "utf8");
}

async function readExistingFile() {
  try {
    return await readFile(galleryPath, "utf8");
  } catch {
    return "";
  }
}

function archiveTag(date = new Date()) {
  const shanghai = new Date(date.getTime() + 8 * 60 * 60 * 1000);
  return `gallery-${shanghai.toISOString().slice(0, 10)}`;
}

function delay(ms) {
  return new Promise((resolveDelay) => setTimeout(resolveDelay, ms));
}

function browserUserAgent() {
  return "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";
}
