// This file is generated by scripts/update-gallery.mjs.
// Updated at 2026-08-22T16:35:24.581Z.
export const ARCHIVE_TAG = "gallery-2026-08-23";
export const GALLERY = [
  "https://i.pixiv.re/img-master/img/2010/11/28/00/04/17/14850801_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2021/07/19/00/00/07/91340782_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2025/11/06/19/47/18/137163191_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2025/06/07/13/09/04/131273283_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2025/04/27/13/50/26/129753314_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2019/11/03/23/06/43/77637615_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2025/06/02/00/00/05/131077131_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2020/09/07/20/14/39/84221844_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2020/09/07/22/03/17/84224587_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2018/09/19/00/00/06/70764030_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2017/11/21/00/00/06/65978954_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2021/07/06/01/22/23/91044559_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2024/10/19/20/33/45/123484101_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2022/11/04/15/54/31/102504586_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2020/06/04/22/53/37/82090744_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2022/05/12/19/00/02/98293770_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2024/07/20/20/57/39/120702792_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2012/08/07/01/15/32/29182900_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2022/03/20/21/06/38/97053734_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2017/08/16/12/46/17/64446344_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2020/11/06/19/01/42/85497288_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2023/05/17/00/00/26/108187955_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2021/10/31/05/14/46/93798804_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2025/11/05/02/37/19/137108223_p0_master1200.jpg",
];
