// This file is generated by scripts/update-gallery.mjs.
// Updated at 2026-09-02T19:21:31.185Z.
export const ARCHIVE_TAG = "gallery-2026-09-03";
export const GALLERY = [
  "https://i.pixiv.re/img-master/img/2019/10/07/00/00/03/77153341_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2022/12/02/19/44/45/103278462_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2022/08/05/21/25/58/100255286_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2023/10/14/18/15/38/112542476_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2016/03/16/20/37/38/55845690_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2021/09/30/20/01/20/93124680_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2021/08/18/19/29/57/92081096_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2025/10/10/21/16/15/136106884_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2021/03/06/00/00/03/88238623_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2025/10/16/06/27/14/136329075_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2021/11/09/12/30/00/94019243_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2025/07/28/12/06/08/133207766_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2021/10/17/01/00/41/93492732_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2026/06/25/16/06/40/146434165_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2018/11/27/17/49/17/71856772_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2024/10/31/01/44/10/123834455_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2018/07/20/21/30/06/69778128_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2025/04/28/20/31/02/129802836_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2023/08/27/17/45/41/111207559_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2025/04/06/13/24/56/129014468_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2022/11/01/02/42/45/102412322_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2023/09/11/21/35/50/111642317_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2021/04/02/20/51/59/88882013_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2026/07/03/17/54/14/146761622_p1_master1200.jpg",
];
