// This file is generated by scripts/update-gallery.mjs.
// Updated at 2026-09-15T19:40:06.974Z.
export const ARCHIVE_TAG = "gallery-2026-09-16";
export const GALLERY = [
  "https://i.pixiv.re/img-master/img/2022/12/03/18/21/58/103303990_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2025/12/19/00/00/24/138759646_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2018/01/31/01/37/21/67043397_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2023/10/25/20/52/37/112843827_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2023/07/30/00/02/37/110353731_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2022/11/26/11/38/05/103105017_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2022/05/12/00/20/19/98281065_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2024/10/19/22/47/42/123488995_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2022/09/18/00/52/53/101298640_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2025/01/14/14/09/41/126211723_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2025/08/12/18/11/08/133797308_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2022/01/19/19/00/01/95632391_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2022/04/01/00/00/41/97311950_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2024/11/14/21/48/54/124296074_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2020/07/29/18/07/11/83305634_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2022/07/17/00/24/54/99774714_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2022/07/04/00/30/06/99487706_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2021/10/14/00/00/01/93427423_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2018/02/20/21/00/00/67375446_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2022/05/28/14/57/56/98658527_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2022/07/03/17/18/46/99475169_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2024/12/28/12/06/51/125622058_p0_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2021/10/26/12/25/09/93694166_p1_master1200.jpg",
  "https://i.pixiv.re/img-master/img/2013/06/17/03/09/27/36445140_p0_master1200.jpg",
];
